local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
return {
  s({ trig = "@a", wordTrig = false, snippetType = "autosnippet" }, { t "\\alpha" }),
  s({ trig = "@b", wordTrig = false, snippetType = "autosnippet" }, { t "\\beta" }),
  s({ trig = "@g", wordTrig = false, snippetType = "autosnippet" }, { t "\\gamma" }),
  s({ trig = "@d", wordTrig = false, snippetType = "autosnippet" }, { t "\\delta" }),
  s({ trig = "@en", wordTrig = false, snippetType = "autosnippet" }, { t "\\epsilon" }),
  s({ trig = "@ve", wordTrig = false, snippetType = "autosnippet" }, { t "\\varepsilon" }),
  s({ trig = "@z", wordTrig = false, snippetType = "autosnippet" }, { t "\\zeta" }),
  s({ trig = "@et", wordTrig = false, snippetType = "autosnippet" }, { t "\\eta" }),
  s({ trig = "@th", wordTrig = false, snippetType = "autosnippet" }, { t "\\theta" }),
  s({ trig = "@i", wordTrig = false, snippetType = "autosnippet" }, { t "\\iota" }),
  s({ trig = "@k", wordTrig = false, snippetType = "autosnippet" }, { t "\\kappa" }),
  s({ trig = "@l", wordTrig = false, snippetType = "autosnippet" }, { t "\\lambda" }),
  s({ trig = "@m", wordTrig = false, snippetType = "autosnippet" }, { t "\\mu" }),
  s({ trig = "@n", wordTrig = false, snippetType = "autosnippet" }, { t "\\nu" }),
  s({ trig = "@pi", wordTrig = false, snippetType = "autosnippet" }, { t "\\pi" }),
  s({ trig = "@r", wordTrig = false, snippetType = "autosnippet" }, { t "\\rho" }),
  s({ trig = "@s", wordTrig = false, snippetType = "autosnippet" }, { t "\\sigma" }),
  s({ trig = "@vs", wordTrig = false, snippetType = "autosnippet" }, { t "\\varsigma" }),
  s({ trig = "@t", wordTrig = false, snippetType = "autosnippet" }, { t "\\tau" }),
  s({ trig = "@f", wordTrig = false, snippetType = "autosnippet" }, { t "\\phi" }),
  s({ trig = "@vf", wordTrig = false, snippetType = "autosnippet" }, { t "\\varphi" }),
  s({ trig = "@ch", wordTrig = false, snippetType = "autosnippet" }, { t "\\chi" }),
  s({ trig = "@ps", wordTrig = false, snippetType = "autosnippet" }, { t "\\psi" }),
  s({ trig = "@o", wordTrig = false, snippetType = "autosnippet" }, { t "\\omega" }),
  s({ trig = "@x", wordTrig = false, snippetType = "autosnippet" }, { t "\\xi" }),

  s({ trig = "@A", wordTrig = false, snippetType = "autosnippet" }, { t "\\Alpha" }),
  s({ trig = "@B", wordTrig = false, snippetType = "autosnippet" }, { t "\\Beta" }),
  s({ trig = "@G", wordTrig = false, snippetType = "autosnippet" }, { t "\\Gamma" }),
  s({ trig = "@D", wordTrig = false, snippetType = "autosnippet" }, { t "\\Delta" }),
  s({ trig = "@En", wordTrig = false, snippetType = "autosnippet" }, { t "\\Epsilon" }),
  s({ trig = "@Z", wordTrig = false, snippetType = "autosnippet" }, { t "\\Zeta" }),
  s({ trig = "@Et", wordTrig = false, snippetType = "autosnippet" }, { t "\\Eta" }),
  s({ trig = "@Th", wordTrig = false, snippetType = "autosnippet" }, { t "\\Theta" }),
  s({ trig = "@I", wordTrig = false, snippetType = "autosnippet" }, { t "\\Iota" }),
  s({ trig = "@K", wordTrig = false, snippetType = "autosnippet" }, { t "\\Kappa" }),
  s({ trig = "@L", wordTrig = false, snippetType = "autosnippet" }, { t "\\Lambda" }),
  s({ trig = "@M", wordTrig = false, snippetType = "autosnippet" }, { t "\\Mu" }),
  s({ trig = "@N", wordTrig = false, snippetType = "autosnippet" }, { t "\\Nu" }),
  s({ trig = "@Pi", wordTrig = false, snippetType = "autosnippet" }, { t "\\Pi" }),
  s({ trig = "@R", wordTrig = false, snippetType = "autosnippet" }, { t "\\Rho" }),
  s({ trig = "@S", wordTrig = false, snippetType = "autosnippet" }, { t "\\Sigma" }),
  s({ trig = "@T", wordTrig = false, snippetType = "autosnippet" }, { t "\\Tau" }),
  s({ trig = "@F", wordTrig = false, snippetType = "autosnippet" }, { t "\\Phi" }),
  s({ trig = "@Chi", wordTrig = false, snippetType = "autosnippet" }, { t "\\Chi" }),
  s({ trig = "@Ps", wordTrig = false, snippetType = "autosnippet" }, { t "\\Psi" }),
  s({ trig = "@O", wordTrig = false, snippetType = "autosnippet" }, { t "\\Omega" }),
  s({ trig = "@X", wordTrig = false, snippetType = "autosnippet" }, { t "\\Xi" }),
}
