#!/bin/bash

set -eu

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
PATH=$PATH:$SCRIPT_DIR

# Prints the file and the directory it is in if last is provided
formatted1=$(format "$1")
formatted2=$(format "$2")
if [[ $(realpath -smL "$1") = $(realpath -smL "$2") ]]; then
  echo "$formatted1 is already linked to $formatted2. Skipping..."
  exit 0
elif [[ -e $2 ]]; then
  if ask "File $formatted2 exists. Do you want to replace it? (y/n) "; then
    echo "Deleting $formatted2 ..."
    rm -rf "$2"
  else
    echo "Skipping..."
    exit 0
  fi
fi

echo "Linking $formatted1 to $formatted2..."
ln -s "$(realpath -sm "$1")" "$(realpath -sm "$2")"
exit 0
