#!/bin/bash

set -eu

echo "Setting up home directory"

# source: https://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FILES_DIR="$SCRIPT_DIR"/../..
PATH=$PATH:$SCRIPT_DIR

setup-alacritty() {
  local mainconfdir="$1/alacritty"
  local defaultconf="$mainconfdir/default.toml"
  if ! [ -e "$mainconfdir" ] || ! [ -e "$defaultconf" ]; then
    return 0;
  fi
  local mainconf="$mainconfdir/alacritty.toml"
  touch "$mainconf" 
  echo "import = [$defaultconf]" > "$mainconf"
  return 0;
}


for file in "$FILES_DIR"/*; do
  filename=${file##*/}
  case $filename in
    "setup")
      ;;
    "config")
      confdir="${XDG_CONFIG_HOME:-$HOME/.config}"
      ndlink "$file" "$confdir" 
      setup-alacritty "$confdir"
      ;;
    "local")
      [[ -d "$file/share" ]] && ndlink "$file/share" "${XDG_DATA_HOME:-$HOME/.local/share}"
      [[ -d "$file/state" ]] && ndlink "$file/state" "${XDG_STATE_HOME:-$HOME/.local/state}"
      ;;
    "x"*)
      [[ -e "$HOME/.$filename" ]] || cp "$file" "$HOME/.$filename"
      ;;
    *)
      nlink "$file" "$HOME/.$filename"
      ;;
  esac
done

