#!/usr/bin/bash

export ask()
{
  while true; do
    echo -n $1
    read -r answer;
    case $answer in
      [yY]) 
        return 0;;
      [nN]) 
        return 1;;
      * ) echo "Wrong answer! Try again";;
    esac
  done
}

nlink ()
{
  if [[ -a $2 ]]; then
    if ask "File or directory $2 exists. Do you want to replace it? (y/n) ";
    then
      echo "Deleting $2 ..."
    else
      echo "Skipping..."
      return 0
    fi
  fi
  echo "Linking $1 to $2..."
  ln -s "$1" "$2"
  return 0;
}

echo "Setting up home directory"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ME=${0##*/}

for file in "$SCRIPT_DIR"/*; do
  case $file in
    "$SCRIPT_DIR/$ME")
      ;;
    "$SCRIPT_DIR/config")
      if [[ -n $XDG_CONFIG_HOME ]]; then
        nlink "$file" "$XDG_CONFIG_HOME"        
      else
        nlink "$file" "$HOME/.${file##*/}"
      fi
      ;;
    *)
      nlink "$file" "$HOME/.${file##*/}"
      ;;
  esac
done

if ask "Do you want to install needed programs?"; then
  if ask "Install needed fonts?"
  then
    /usr/bin/curl -s https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest \
  | /usr/bin/grep "JetBrainsMono.tar.xz" \
  | /usr/bin/cut -d : -f 2,3 \
  | /usr/bin/tr -d \" \
  | /usr/bin/wget -qi - \
  
